services:
  pythia-chat:
    build: .
    ports:
      - "7860:7860"
    environment:
      - HF_HUB_ENABLE_HF_TRANSFER=0
      - PYTHONUNBUFFERED=1
    tty: true
    volumes:
      - model-cache:/root/.cache/huggingface
      - ./web.py:/app/web.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  model-cache:
